気持ちっしょ！

diff --git a/.github/workflows/infra.preview-deploy.yml b/.github/workflows/infra.preview-deploy.yml
--- a/.github/workflows/infra.preview-deploy.yml
+++ b/.github/workflows/infra.preview-deploy.yml
@@ -30,7 +30,6 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       TF_PLAN_EXITCODE: ${{ steps.plan.outputs.exitcode }}
-      # TF_PLAN_EXITCODE: ${{ env.exitcode }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -67,18 +66,33 @@ jobs:
             -no-color \
             -input=false \
             -detailed-exitcode
-          #echo "exitcode=$?" >> $GITHUB_OUTPUT
-          # echo "TF_PLAN_EXITCODE=$?" >> $GITHUB_ENV
-          # echo "exitcode=$?" >> $GITHUB_ENV
-          # echo "::set-output name=exitcode::$?"
 
-      - name: Debug plan exit code
+          ############上記set +eでエラー無視をしているが、if文でエラーを検知し、止める。
+          # terraform plan の 終了コードを変数に保存
+          code=$?
+          echo "Terraform plan exit code is $code"
+          # 1（エラー）の場合はスクリプト停止させる。
+          #2（変更あり）の場合はスクリプトを続行。
+          #0（変更なし）の場合はスクリプトを終了させる。
+          if [ $code -eq 1 ]; then
+            echo "Terraform plan failed with exit code 1. Stopping script."
+            exit 1
+          elif [ $code -eq 2 ]; then
+            echo "Terraform plan succeeded with exit code 2 (changes present). Continuing script."
+          elif [ $code -eq 0 ]; then
+            echo "Terraform plan finished with exit code 0 (no changes). Skipping further steps."
+          fi
+          ############
+          # exit codeをGitHub Actionsの出力に設定
+          echo "exitcode=$?" >> $GITHUB_OUTPUT
+
+      - name: Debug plan exit code #デバッグ用
+        # if: always() #常に実行する
         if: always()
         run: |
           echo "Plan exit code is: ${{ steps.plan.outputs.exitcode }}"
 
       - name: Slack notify
-        # if: ${{ always() && steps.plan.outputs.exitcode == '2' }} #planのdetailed-exitcodeが2のときのみ実行する
         if: steps.plan.outputs.exitcode == '2' #planのdetailed-exitcodeが2のときのみ実行する
 
         uses: slackapi/slack-github-action@v1.22.0
