修正8

diff --git a/.github/workflows/infra.preview-deploy.yml b/.github/workflows/infra.preview-deploy.yml
--- a/.github/workflows/infra.preview-deploy.yml
+++ b/.github/workflows/infra.preview-deploy.yml
@@ -17,7 +17,7 @@ env:
   AWS_REGION: ap-northeast-1
   TF_VERSION: 1.2.8
   TF_PROJECT: tastylog
-  TF_ENVIROMENT: dev
+  TF_ENVIROMENT: dry-run
 
 defaults:
   run:
@@ -65,22 +65,21 @@ jobs:
             -no-color \
             -input=false \
             -detailed-exitcode
-          echo "exitcode=$?" >> $GITHUB_OUTPUT
+          #echo "exitcode=$?" >> $GITHUB_OUTPUT
 
-      - name: Debug exit code
-        run: |
-          echo "Terraform plan exit code: ${{ steps.plan.outputs.exitcode }}"
-
+      #- name: Debug exit code
+        #run: |
+          #echo "Terraform plan exit code: ${{ steps.plan.outputs.exitcode }}"
       # 重要：デバッグ用に変更があるかどうかを確認
-      - name: Set has changes
-        id: set_changes
-        run: |
-          if [ "${{ steps.plan.outputs.exitcode }}" == "2" ]; then
-            echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
-          else
-            echo "HAS_CHANGES=false" >> $GITHUB_OUTPUT
-          fi
-          echo "Has changes: $([ "${{ steps.plan.outputs.exitcode }}" == "2" ] && echo 'YES' || echo 'NO')"
+      # - name: Set has changes
+      #   id: set_changes
+      #   run: |
+      #     if [ "${{ steps.plan.outputs.exitcode }}" == "2" ]; then
+      #       echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
+      #     else
+      #       echo "HAS_CHANGES=false" >> $GITHUB_OUTPUT
+      #     fi
+      #     echo "Has changes: $([ "${{ steps.plan.outputs.exitcode }}" == "2" ] && echo 'YES' || echo 'NO')"
 
         #Slack通知
       - name: Slack notify
@@ -117,7 +116,7 @@ jobs:
     name: "Deploy"
     runs-on: ubuntu-latest
     needs: preview
-    if: needs.preview.outputs.TF_PLAN_EXITCODE == '2'
+    if: needs.preview.outputs.TF_PLAN_EXITCODE == 2
     #planのdetailed-exitcodeが2のときのみ実行する
     environment: production
     steps:
